# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.


# Conversion
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge

# Permalinks
permalink:        /:categories/:title/


# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title:            'Writing is Important'
tagline:          'archiving & sharing'
description:      'Big Data Engineer -> decision by data learning'
url:              https://mahadisiregar.com

author:
  name:           Mahadi Siregar
  email:          regar.016@gmail.com
  github:         regar016
  facebook:       regar.016
  linkedin:       mahadisiregar
  instagram:      mahadi.siregar
  twitter:        MahadiSiregar
  url:            https://mahadisiregar.com
  bio:            Big Data Engineer - Java Developer - Scala - AngularJS 1 - PHP
  email_md5:      9b1f20defba8dbbc3d1063c0d6a29b47

# Build settings
theme: minima
plugins:
  - jekyll-feed

paginate:         5

# Google Analytics
#google_analytics_tracking_id: UA-36102948-1

# Facebook Comments
facebook_appid: 1441035232668468

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
